### ISSUE TITLE
plugin does not work for PLOS articles

### ISSUE THREAD

**Issue by jmnicholson** [scitedotai/scite-extension#1]
I have tested a few PLOS articles on Chrome and Firefox and the badge does not display at all on chrome and incorrectly on FireFox. https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0217654

Unpaywall plugin does seem to work well on PLOS.

<img width="133" alt="Screen Shot 2019-07-09 at 2 29 18 PM" src="https://user-images.githubusercontent.com/13700907/60913719-feaa3c00-a255-11e9-9d52-0ae307597fec.png">

**Comment by bananaoomarang** [comment]
For this example we don't have a metadata unfortunately: https://scite.ai/reports/10.1371/journal.pone.0217654

**Comment by jmnicholson** [comment]
Tested on an older article and it works.
