### ISSUE TITLE
DOI does not work for Springer article

### ISSUE THREAD

**Issue by jmnicholson** [scitedotai/scite-extension#3]
scite plugin does not show up on chrome or Firefox for this article: https://link.springer.com/article/10.1007%2Fs10071-018-1172-4

Or this Elsevier one: https://www.sciencedirect.com/science/article/pii/S2590162118300017

Unpaywall plugin shoes up on both.

**Comment by bananaoomarang** [comment]
Empty tally: https://api.scite.ai/tallies/10.1007/s10071-018-1172-4. I believe it won't show in the case where total=0, can change that behavior if we want.

**Comment by jmnicholson** [comment]
I think it would be good to show even where it is 0 0 0
