### ISSUE TITLE
Chrome and Firefox extension SERP badge rendering issue in Semantic Scholar

### ISSUE THREAD

**Issue by lindawagner** [scitedotai/scite-extension#64]
Hurray! I now see scite badges in Semantic Scholar SERP ([[GH-4003] add semantic scholar](https://github.com/scitedotai/scite-extension/commit/ffd69a9cf507068b66c29a920a00b5e3232ae083))!

Badges render as expected on p. 1 of SERP - e.g. https://www.semanticscholar.org/search?q=malaria&sort=relevance
But advancing to page 2 or 3, etc of SERP using the arrows located at the bottom of the page results in a group of orphan scite badges. This occurs in both Firefox and Chrome. I didn't test in other browsers.

### Repro
Go to Semantic Scholar at www.semanticscholar.org and enter a term in the search bar. For instance 'malaria' https://www.semanticscholar.org/search?q=malaria&sort=relevance

At the bottom of the first page of search results, click the arrow to advance to page 2.
:<img width="223" alt="Screen Shot 2022-03-23 at 3 42 28 PM" src="https://user-images.githubusercontent.com/57689130/159808225-8813c1a2-ce41-49ac-b91f-2f40eba91c49.png">

Advancing to page 2 onward results in a bunch of orphan badges. (Note: This only occurs when advancing using the arrows. The issue does not occur when using direct links to SERPs (eg p2 of malaria results https://www.semanticscholar.org/search?q=malaria&sort=relevance&page=2)
<img width="822" alt="Screen Shot 2022-03-23 at 3 41 30 PM" src="https://user-images.githubusercontent.com/57689130/159808327-bfb33795-81f2-486d-9f7f-26c755ace472.png">
<img width="975" alt="Screen Shot 2022-03-23 at 3 46 09 PM" src="https://user-images.githubusercontent.com/57689130/159808898-e544b790-29ec-4832-ab16-5c22a6fd83ec.png">

**Comment by domenicrosati** [comment]
Hey thanks for raising this... I had thought I had prevented this from happening as I noticed it and thought I fixed in the new release but I will be sure cut a release that fixes it ASAP apologies for the inconvenience

**Comment by domenicrosati** [comment]
@lindawagner I have [released a fix for this](https://github.com/scitedotai/scite-extension/pull/65) (unfortunately removing semantic scholar badges for now) It is already out on Firefox but still waiting for approval in Chrome and Safari.

Thanks!

**Comment by domenicrosati** [comment]
Closing since a fix is released.
